### ISSUE TITLE
Custom emotes not working

### ISSUE THREAD

**Issue by 0xCUB3** [riolubruh/NitroPerks#1]
They just don't show up and are blocked behind the nitro wall.

**Comment by riolubruh** [comment]
Please replace your version of 0PluginLibrary / ZeresPluginLibrary with the one provided (or any version before 2.x.x) and come back to me if the issue isn't resolved. I have updated the readme to make people aware of this.

**Comment by 0xCUB3** [comment]
ok cool, thanks. This made it work. lmk if the issue gets fixed with 2.x.x and newer so I can re-update 👍

**Comment by riolubruh** [comment]
No problem!
A big part of why it doesnt work with 2.x.x is because Zere removed the DiscordAPI module in that version, which this plugin requires.
As for re-updating, I have not found that necessary yet. I have lots of plugins that use ZeresPluginLibrary and they all seem to work with the version of ZeresPluginLibrary that is provided, which is 1.3.6. So re-updating should not be necessary unless Zere adds or changes something really major or important that plugins really need, which, to be honest, is unlikely considering we're talking about Zere.

**Comment by 0xCUB3** [comment]
Alright that sounds good. Yeah, it's unlikely that Zere will make any major changes anytime soon. 

Just out of curiosity, if you don't mind me asking, how did you get into/learn how to do discord client modding and plugin dev?

**Comment by riolubruh** [comment]
It's mostly because the original developer abandoned this plugin and it was buggy so I decided that I wanted to fix it.
As for learning, a lot of my learning is actually from me learning web development, since I needed to learn HTML, CSS, and JS for my website. If you're curious, the URL to that is [https://stuff.riolubruh.repl.co](https://stuff.riolubruh.repl.co), however most of it is stuff that is specifically for avoiding web filters / censorship cause I was bored at school so I decided to troll the admins by making my own websites, proxies, hosting my own games and emulators, etc. It's pretty cool!
I don't actually know that much about betterdiscord plugin development overall, since there isn't really documentation on it. Having a good handle on JavaScript is really the most important part so far.

**Comment by 0xCUB3** [comment]
That's really cool! The website looks awesome. I am struggling to start developing plugins myself because of the lack of documentation - I just don't know where to start :(
I know JS pretty well so in theory it shouldn't be too bad.

I'm just like you - gotta beat the system at school lol

**Comment by riolubruh** [comment]
Nice, lol. To be honest, I doubt that I could write a plugin from scratch just because of the lack of *any* documentation; that's what's nice about forking a plugin that's been abandoned, the framework is already there for you so you can focus on the actual function of the plugin itself with the added bonus that the original developer won't interfere.

**Comment by 0xCUB3** [comment]
Nice, I might just do the same thing lol. You seem like a nice person, do you want to have a contact on Discord? I'm 0xCUBE#4315 if you want. No pressure though :)

**Comment by riolubruh** [comment]
Sure, idrc. My Discord is Riolubruh#0301, which I give out sometimes.

I'm curious, where did you hear about the plugin from?

**Comment by 0xCUB3** [comment]
I just found it by searching "betterdiscord nitro" on github since I don't like Freemoji nor devilbro plugins so I wanted to see if there was something else.

**Comment by riolubruh** [comment]
Nice. Oh yeah, that reminds me, I should probably add some tags to the github so it's easier to find. lul

**Comment by 0xCUB3** [comment]
lol good idea. btw this is a much better nitro plugin than anything I've ever used.

**Comment by riolubruh** [comment]
Thanks! There are a couple other Nitro plugins but most of them don't compare to this one for sure!
There's also a couple other people's forks/mirrors of NitroPerks but afaik none of them have some of the features of mine and I don't think anybody else is actively maintaining it at this time.
I will admit though that there are a couple of versions of NitroPerks that fixed the profile picture and shit like that and also I think there is a version of NitroPerks someone made that fixes the issue with ZeresPluginLibrary 2.x.x so maybe I could take the fix for that from _those_ and make mine to be really the **ultimate nitro plugin**..? 
Although I don't really care about the clientside profile picture stuff, like, at all, and I don't think pretty much anybody else does because it's literally completely useless since it _is_ **_clientside_** so nobody else sees it anyways and you can just use another plugin if you _really_ want that client side profile picture stuff.

**Comment by 0xCUB3** [comment]
👀 yeah that would be cool. I will dig around too

**Comment by riolubruh** [comment]
Reopening this issue because I am going to be removing the need for the outdated version of ZeresPluginLibrary soon.
