### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by Pashata105c** [riolubruh/NitroPerks#2]
Should this be able to change the banner to anything and profile picture to gif or is it strictly bigger files and screen sharing?

**Comment by riolubruh** [comment]
The plugin is for emotes and screen sharing. You cannot upload GIF profile pictures or banners without Nitro since that is server side. If you want client-side profile picture / banner options then you can use another plugin for that, such as EditUsers.
Also you can use the FreeStickers plugin with this as well.

**Comment by riolubruh** [comment]
_If_ enough people request it, I will consider adding client-side profile features.

**Comment by Pashata105c** [comment]
it is a cool feature to have if you wanna do it tho we can leave without it. Thank you for the nitro plugin bro works good
