### ISSUE TITLE
Implement emote uploading like in EmoteReplacer or fix compatibility with EmoteReplacer

### ISSUE THREAD

**Issue by UltraJew** [riolubruh/NitroPerks#4]
Could you make it an option to remove FreeStickers as sending the emote image instead of the Link is much more useful and versitile.
I was not able to use them both at once unfortunately.

**Comment by riolubruh** [comment]
I think you may be a little confused, but I understand what you are asking.
FreeStickers is a plugin that allows you to use community stickers, it does not do anything with emotes. However, yes, this plugin does have some compatibility problems due to the premiumType being modified client-side confusing some plugins into thinking that the user actually has premium when they do not.
So basically what you are asking is that EmoteReplacer be compatible with this plugin. It would likely be easier to modify EmoteReplacer to fix the issue as a hotfix, contact me on Discord if you want that; Riolubruh#0301.

**Comment by riolubruh** [comment]
EmoteReplacer works fine with this plugin, as far as I can tell.
EmoteReplacer is not a plugin for modifying the existing emote system, it uses the prefix **;**

**Comment by riolubruh** [comment]
> Could you make it an option to remove FreeStickers as sending the emote image instead of the Link is much more useful and versitile. I was not able to use them both at once unfortunately.
Here's a hackfix for you, pal, sorry about that! All this does is remove the function in EmoteReplacer that checks for Premium. @UltraJew 
[EmoteReplacer.plugin.zip](https://github.com/riolubruh/NitroPerks/files/8682748/EmoteReplacer.plugin.zip)

**Comment by UltraJew** [comment]
Thanks a lot, though I can't get this to work. My issue is that when using your NitroPerks plugin (especially the Screenshare feature), EmoteReplacer breaks. 
As in Emotes cannot be sent as images anymore, I was suggestion you to implement ER. over FreeStickers because you cannot use it on servers that block links.
This basically has the exact functionality of your "version" when using the Emote Bypass setting. Not sure what would be more ideal.

**Comment by UltraJew** [comment]
Dope. Would love to see this done, would really be the _best nitro_ plugin out there : )

**Comment by riolubruh** [comment]
Okay, I've made some progress on this! It's still got a couple bugs to work out, but it's getting very close! I'll upload the current version now, but I wouldn't recommend using it yet as it is still very work-in-progress and you'll get Clyde screaming at you for no reason

**Comment by UltraJew** [comment]
Nice! Yeah Clyde is so aggressive lol. Hope you get it figured out, made some huge progress already 👍

**Comment by riolubruh** [comment]
It is finally complete!
I hope it's everything you hoped it to be! (cause I'm not even gonna _bother_ trying to implement some of the stuff in EmoteReplacer like modifiers XD)

You better share this plugin now LOL
Have a great day!
